# Generated by Django 5.0.6 on 2024-07-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor_user',
            name='fk_school',
        ),
    ]
