# Generated by Django 5.0.6 on 2024-07-02 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor_user',
            options={'ordering': ['professor_auth_user'], 'verbose_name': 'Professor'},
        ),
        migrations.AddField(
            model_name='professor_user',
            name='fk_academic_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.academic_education', verbose_name='Academic Formation'),
        ),
        migrations.AddField(
            model_name='professor_user',
            name='fk_professional_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.professional_history', verbose_name='Professional History'),
        ),
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, unique=True)),
                ('school_state', models.CharField(choices=[('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('PR', 'Paraná'), ('SP', 'São Paulo'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('GO', 'Goiás'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('BA', 'Bahia'), ('PE', 'Pernanbuco'), ('MA', 'Maranhão'), ('AL', 'Alagoas'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paaraíba'), ('CE', 'Ceará'), ('SE', 'Sergipe'), ('PI', 'Piauí'), ('TO', 'Tocantins'), ('PA', 'Pará'), ('AP', 'Amapá'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('AM', 'Amazonas'), ('AC', 'Acre')], max_length=2)),
                ('school_auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'school_name',
                'ordering': ['school_auth_user'],
            },
        ),
    ]
