# Generated by Django 5.0.6 on 2024-06-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_academic_education_profession_professional_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
