# Generated by Django 5.0.6 on 2024-06-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customuser_confirmation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
    ]
