# Generated by Django 5.0.6 on 2024-07-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
