# Generated by Django 5.0.6 on 2024-07-11 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('login', '0002_remove_professor_user_fk_school'),
        ('perfil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_user',
            field=models.ManyToManyField(through='perfil.Note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='fk_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.school', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fk_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.content', verbose_name='Conteudo do comentário'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subject', verbose_name='Matéria do conteúdo'),
        ),
    ]
