# Generated by Django 5.0.6 on 2024-07-05 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('perfil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='notes',
            field=models.ManyToManyField(null=True, through='perfil.Note', to=settings.AUTH_USER_MODEL),
        ),
    ]
