# Generated by Django 5.0.6 on 2024-07-05 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_content_notes'),
        ('perfil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='notes',
        ),
        migrations.AddField(
            model_name='content',
            name='content_user',
            field=models.ManyToManyField(through='perfil.Note', to=settings.AUTH_USER_MODEL),
        ),
    ]
