# Generated by Django 5.0.6 on 2024-07-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_content_notes_content_content_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_position',
            field=models.IntegerField(default=1),
        ),
    ]
