# Generated by Django 5.0.6 on 2024-07-09 17:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_content_content_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='fk_school',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_pdf',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='pdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content_video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
