# Generated by Django 5.0.6 on 2024-07-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_content_fk_school_alter_content_content_pdf_and_more'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='fk_school',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='login.school', verbose_name='Escola'),
            preserve_default=False,
        ),
    ]
