# Generated by Django 5.0.6 on 2024-06-11 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('perfil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_professor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.professor_user', verbose_name='Professor do conteúdo'),
        ),
        migrations.AddField(
            model_name='content',
            name='notes',
            field=models.ManyToManyField(through='perfil.Note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='content_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject', verbose_name='Matéria do conteúdo'),
        ),
    ]
